// <auto-generated />
namespace SisTarefas.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class SqlTeste : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SqlTeste));
        
        string IMigrationMetadata.Id
        {
            get { return "202102230355264_SqlTeste"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
